# Generated by Django 6.0.3 on 2026-06-08 17:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='curso',
            old_name='Descricao',
            new_name='descricao',
        ),
        migrations.AlterField(
            model_name='curso',
            name='data',
            field=models.DateField(blank=True, null=True, verbose_name='Data de início'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
